name: ojembaa_courier
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  dropdown_search: ^5.0.6
  firebase_core: ^2.8.0
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^16.2.0
  flutter_riverpod: ^2.4.2
  flutter_svg: ^2.0.7
  geolocator: ^10.1.0
  http_parser: ^4.0.2
  image_picker: ^1.0.4
  path: ^1.8.3
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: QanelasSoft
      fonts:
        - asset: assets/fonts/QanelasSoft/QanelasSoft-Thin.otf
          weight: 100
        - asset: assets/fonts/QanelasSoft/QanelasSoft-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/QanelasSoft/QanelasSoft-Light.otf
          weight: 300
        - asset: assets/fonts/QanelasSoft/QanelasSoft-Regular.otf
          weight: 400
        - asset: assets/fonts/QanelasSoft/QanelasSoft-Medium.otf
          weight: 500
        - asset: assets/fonts/QanelasSoft/QanelasSoft-SemiBold.otf
          weight: 600
        - asset: assets/fonts/QanelasSoft/QanelasSoft-Bold.otf
          weight: 700
        - asset: assets/fonts/QanelasSoft/QanelasSoft-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/QanelasSoft/QanelasSoft-Black.otf
          weight: 900

    - family: Work Sans
      fonts:
        - asset: assets/fonts/WorkSans/WorkSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/WorkSans/WorkSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/WorkSans/WorkSans-Light.ttf
          weight: 300
        - asset: assets/fonts/WorkSans/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/WorkSans/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/WorkSans/WorkSans-Bold.ttf
          weight: 800
